//! Human-readable S-57 names, for the object-query bubble.
//!
//! Generated from the IHO S-57 Ed 3.1 tables OpenCPN ships
//! (`s57objectclasses.csv`, `attdecode.csv`) so a picked object reads the way
//! it does in OpenCPN: "Buoy, cardinal" rather than BOYCAR, and "north
//! cardinal mark" rather than CATCAM 1.
//!
//! Both tables are sorted, and binary-searched; tests assert the ordering.

/// Object class acronym to its full name.
const OBJECT_CLASSES: &[(&str, &str)] = &[
    ("$AREAS", "Cartographic area"),
    ("$COMPS", "Compass"),
    ("$CSYMB", "Cartographic symbol"),
    ("$LINES", "Cartographic line"),
    ("$TEXTS", "Text"),
    ("ACHARE", "Anchorage area"),
    ("ACHBRT", "Anchor berth"),
    ("ACHPNT", "Anchor"),
    ("ADMARE", "Administration area (Named)"),
    ("AIRARE", "Airport / airfield"),
    ("ANNOTA", "Annotation"),
    ("BCNCAR", "Beacon, cardinal"),
    ("BCNISD", "Beacon, isolated danger"),
    ("BCNLAT", "Beacon, lateral"),
    ("BCNSAW", "Beacon, safe water"),
    ("BCNSPP", "Beacon, special purpose/general"),
    ("BERTHS", "Berth"),
    ("BOYCAR", "Buoy, cardinal"),
    ("BOYINB", "Buoy, installation"),
    ("BOYISD", "Buoy, isolated danger"),
    ("BOYLAT", "Buoy, lateral"),
    ("BOYSAW", "Buoy, safe water"),
    ("BOYSPP", "Buoy, special purpose/general"),
    ("BRIDGE", "Bridge"),
    ("BUAARE", "Built-up area"),
    ("BUIREL", "Building, religous"),
    ("BUISGL", "Building, single"),
    ("CANALS", "Canal"),
    ("CANBNK", "Canal bank"),
    ("CAUSWY", "Causeway"),
    ("CBLARE", "Cable area"),
    ("CBLOHD", "Cable, overhead"),
    ("CBLSUB", "Cable, submarine"),
    ("CGUSTA", "Coastguard station"),
    ("CHKPNT", "Checkpoint"),
    ("CHNWIR", "Chain/Wire"),
    ("COALNE", "Coastline"),
    ("CONVYR", "Conveyor"),
    ("CONZNE", "Contiguous zone"),
    ("COSARE", "Continental shelf area"),
    ("CRANES", "Crane"),
    ("CTNARE", "Caution area"),
    ("CTRPNT", "Control point"),
    ("CTSARE", "Cargo transshipment area"),
    ("CURENT", "Current - non - gravitational"),
    ("CUSZNE", "Custom zone"),
    ("C_AGGR", "Aggregation"),
    ("C_ASSO", "Association"),
    ("C_STAC", "Stacked on/stacked under"),
    ("DAMCON", "Dam"),
    ("DAYMAR", "Daymark"),
    ("DEPARE", "Depth area"),
    ("DEPCNT", "Depth contour"),
    ("DISMAR", "Distance mark"),
    ("DMPGRD", "Dumping ground"),
    ("DOCARE", "Dock area"),
    ("DRGARE", "Dredged area"),
    ("DRYDOC", "Dry dock"),
    ("DWRTCL", "Deep water route centerline"),
    ("DWRTPT", "Deep water route part"),
    ("DYKCON", "Dyke"),
    ("EXEZNE", "Exclusive Economic Zone"),
    ("FAIRWY", "Fairway"),
    ("FERYRT", "Ferry route"),
    ("FLODOC", "Floating dock"),
    ("FNCLNE", "Fence/wall"),
    ("FOGSIG", "Fog signal"),
    ("FORSTC", "Fortified structure"),
    ("FRPARE", "Free port area"),
    ("FSHFAC", "Fishing facility"),
    ("FSHGRD", "Fishing ground"),
    ("FSHZNE", "Fishery zone"),
    ("GATCON", "Gate"),
    ("GENNAV", "Generic NavAid"),
    ("GRIDRN", "Gridiron"),
    ("HRBARE", "Harbour area (administrative)"),
    ("HRBFAC", "Harbour facility"),
    ("HULKES", "Hulk"),
    ("ICEARE", "Ice area"),
    ("ICNARE", "Incineration area"),
    ("ISTZNE", "Inshore traffic zone"),
    ("LAKARE", "Lake"),
    ("LAKSHR", "Lake shore"),
    ("LIGHTS", "Light"),
    ("LITFLT", "Light float"),
    ("LITVES", "Light vessel"),
    ("LNDARE", "Land area"),
    ("LNDELV", "Land elevation"),
    ("LNDMRK", "Landmark"),
    ("LNDRGN", "Land region"),
    ("LOCMAG", "Local magnetic anomaly"),
    ("LOGPON", "Log pond"),
    ("LOKBSN", "Lock basin"),
    ("MAGVAR", "Magnetic variation"),
    ("MARCUL", "Marine farm/culture"),
    ("MIPARE", "Military practice area"),
    ("MONUMT", "Monument"),
    ("MORFAC", "Mooring/warping facility"),
    ("M_ACCY", "Accuracy of data"),
    ("M_COVR", "Coverage"),
    ("M_CSCL", "Compilation scale of data"),
    ("M_HDAT", "Horizontal datum of data"),
    ("M_HOPA", "Horizontal datum shift parameters"),
    ("M_NPUB", "Nautical publication information"),
    ("M_NSYS", "Navigational system of marks"),
    ("M_PROD", "Production information"),
    ("M_QUAL", "Quality of data"),
    ("M_SDAT", "Sounding datum"),
    ("M_SREL", "Survey reliability"),
    ("M_UNIT", "Units of measurement of data"),
    ("M_VDAT", "Vertical datum of data"),
    ("NAVLNE", "Navigation line"),
    ("NEWOBJ", "New Object"),
    ("OBSTRN", "Obstruction"),
    ("OFSPLF", "Offshore platform"),
    ("OILBAR", "Oil barrier"),
    ("OSPARE", "Offshore production area"),
    ("PILBOP", "Pilot boarding place"),
    ("PILPNT", "Pile"),
    ("PIPARE", "Pipeline area"),
    ("PIPOHD", "Pipeline, overhead"),
    ("PIPSOL", "Pipeline, submarine/on land"),
    ("PONTON", "Pontoon"),
    ("PRCARE", "Precautionary area"),
    ("PRDARE", "Production / storage area"),
    ("PYLONS", "Pylon/bridge support"),
    ("RADLNE", "Radar line"),
    ("RADRFL", "Radar reflector"),
    ("RADRNG", "Radar range"),
    ("RADSTA", "Radar station"),
    ("RAILWY", "Railway"),
    ("RAPIDS", "Rapids"),
    ("RCRTCL", "Recommended route centerline"),
    ("RCTLPT", "Recommended Traffic Lane Part"),
    ("RDOCAL", "Radio calling-in point"),
    ("RDOSTA", "Radio station"),
    ("RECTRC", "Recommended track"),
    ("RESARE", "Restricted area"),
    ("RESTRC", "Generic Boundary"),
    ("RETRFL", "Retro-reflector"),
    ("RIVBNK", "River bank"),
    ("RIVERS", "River"),
    ("ROADWY", "Road"),
    ("RSCSTA", "Rescue station"),
    ("RTPBCN", "Radar transponder beacon"),
    ("RUNWAY", "Runway"),
    ("SBDARE", "Seabed area"),
    ("SEAARE", "Sea area / named water area"),
    ("SILTNK", "Silo / tank"),
    ("SISTAT", "Signal station, traffic"),
    ("SISTAW", "Signal station, warning"),
    ("SLCONS", "Shoreline Construction"),
    ("SLOGRD", "Sloping ground"),
    ("SLOTOP", "Slope topline"),
    ("SMCFAC", "Small craft facility"),
    ("SNDWAV", "Sand waves"),
    ("SOUNDG", "Sounding"),
    ("SPLARE", "Sea-plane landing area"),
    ("SPRING", "Spring"),
    ("SQUARE", "Square"),
    ("STSLNE", "Straight territorial sea baseline"),
    ("SUBTLN", "Submarine transit lane"),
    ("SWPARE", "Swept Area"),
    ("TESARE", "Territorial sea area"),
    ("TIDEWY", "Tideway"),
    ("TOPMAR", "Topmark"),
    ("TOWERS", "Tower"),
    ("TRFLNE", "Traffic Line"),
    ("TSELNE", "Traffic Separation Line"),
    ("TSEZNE", "Traffic Separation Zone"),
    ("TSSBND", "Traffic Separation Scheme  Boundary"),
    ("TSSCRS", "Traffic Separation Scheme Crossing"),
    ("TSSLPT", "Traffic Separation Scheme  Lane part"),
    ("TSSRON", "Traffic Separation Scheme  Roundabout"),
    ("TS_FEB", "Tidal stream - flood/ebb"),
    ("TS_PAD", "Tidal stream panel data"),
    ("TS_PNH", "Tidal stream - non-harmonic prediction"),
    ("TS_PRH", "Tidal stream - harmonic prediction"),
    ("TS_TIS", "Tidal stream - time series"),
    ("TUNNEL", "Tunnel"),
    ("TWRTPT", "Two-way route  part"),
    ("T_HMON", "Tide - harmonic prediction"),
    ("T_NHMN", "Tide - non-harmonic prediction"),
    ("T_TIMS", "Tidal stream - time series"),
    ("UNSARE", "Unsurveyed area"),
    ("UWTROC", "Underwater rock / awash rock"),
    ("VEGATN", "Vegetation"),
    ("WATFAL", "Waterfall"),
    ("WATTUR", "Water turbulence"),
    ("WEDKLP", "Weed/Kelp"),
    ("WRECKS", "Wreck"),
    ("ZEMCNT", "Zero meter contour"),
    ("_extgn", "Light, extinguished"),
    ("_texto", "Text"),
    ("achare", "Anchorage area"),
    ("achbrt", "Anchor berth"),
    ("bcnlat", "Beacon, lateral"),
    ("bcnwtw", "Beacon water-way"),
    ("berths", "Berth"),
    ("boylat", "Buoy, lateral"),
    ("boywtw", "Buoy water-way"),
    ("brgare", "Bridge area"),
    ("bridge", "Bridge"),
    ("bunsta", "Bunker station"),
    ("canbnk", "Canal bank"),
    ("cblohd", "Cable, overhead"),
    ("chkpnt", "Checkpoint"),
    ("comare", "Communication area"),
    ("convyr", "Conveyor"),
    ("cranes", "Crane"),
    ("curent", "Current, non-gravitational"),
    ("depare", "Depth area"),
    ("dismar", "distance mark"),
    ("excnst", "Exceptional navigation structure"),
    ("feryrt", "Ferry route"),
    ("flodoc", "Floating dock"),
    ("gatcon", "Gate"),
    ("hrbare", "Harbour area (administrative)"),
    ("hrbbsn", "Harbour basin"),
    ("hrbfac", "Harbour facility"),
    ("hulkes", "Hulk"),
    ("lg_sdm", "Maximum permitted ship dimensions"),
    ("lg_vsp", "Maximum permitted vessel speed"),
    ("lkbspt", "Lock basin part"),
    ("lokare", "Lock area"),
    ("lokbsn", "Lock basin"),
    ("m_nsys", "Navigational system of marks"),
    ("m_sdat", "Sounding datum"),
    ("m_vdat", "Vertical datum"),
    ("notmrk", "Notice mark"),
    ("pipohd", "Pipeline, overhead"),
    ("ponton", "Pontoon"),
    ("prtare", "port area"),
    ("rdocal", "Radio calling-in point"),
    ("refdmp", "refuse dump"),
    ("resare", "Restricted area"),
    ("rivbnk", "River bank"),
    ("rtplpt", "Route planning point"),
    ("sistat", "Signal station, traffic"),
    ("sistaw", "Signal station, warning"),
    ("slcons", "Shoreline Construction"),
    ("termnl", "terminal"),
    ("tisdge", "Time Schedule - in general"),
    ("topmar", "Top Mark"),
    ("trnbsn", "turning basin"),
    ("uwtroc", "Underwater rock / awash rock"),
    ("vehtrf", "Vehicle transfer"),
    ("wtware", "Waterway area"),
    ("wtwaxs", "waterway axis"),
    ("wtwgag", "Waterway gauge"),
    ("wtwprf", "waterway profile"),
];

/// (attribute acronym, enumerated value) to its meaning.
const ATTRIBUTE_VALUES: &[(&str, u32, &str)] = &[
    ("BCNSHP", 1, "Stake. Pole. Perch. Post"),
    ("BCNSHP", 2, "Withy"),
    ("BCNSHP", 3, "BeaconTower"),
    ("BCNSHP", 4, "Lattice Beacon"),
    ("BCNSHP", 5, "Pile Beacon"),
    ("BCNSHP", 6, "Cairn"),
    ("BCNSHP", 7, "Bouyant Beacon"),
    ("BOYSHP", 1, "conical (nun)"),
    ("BOYSHP", 2, "can (cylindrical)"),
    ("BOYSHP", 3, "spherical"),
    ("BOYSHP", 4, "pillar"),
    ("BOYSHP", 5, "spar (spindle)"),
    ("BOYSHP", 6, "barrel (tun)"),
    ("BOYSHP", 7, "super-buoy"),
    ("BOYSHP", 8, "ice buoy"),
    ("BUISHP", 1, "no specific shape"),
    ("BUISHP", 2, "tower"),
    ("BUISHP", 3, "spire"),
    ("BUISHP", 4, "cupola (dome)"),
    ("BUISHP", 5, "high-rise building"),
    ("BUISHP", 6, "pyramid"),
    ("BUISHP", 7, "cylindrical"),
    ("BUISHP", 8, "spherical"),
    ("BUISHP", 9, "cubic"),
    ("CATACH", 1, "unrestricted anchorage"),
    ("CATACH", 2, "deep water anchorage"),
    ("CATACH", 3, "tanker anchorage"),
    ("CATACH", 4, "explosives anchorage"),
    ("CATACH", 5, "quarantine anchorage"),
    ("CATACH", 6, "sea-plane anchorage"),
    ("CATACH", 7, "small craft anchorage"),
    ("CATACH", 8, "small craft mooring area"),
    ("CATACH", 9, "anchorage for periods up to 24 hours"),
    ("CATACH", 10, "anchorage for a limited period of time"),
    ("CATAIR", 1, "military aeroplane airport"),
    ("CATAIR", 2, "civil aeroplane airport"),
    ("CATAIR", 3, "military heliport"),
    ("CATAIR", 4, "civil heliport"),
    ("CATAIR", 5, "glider arifield"),
    ("CATAIR", 6, "small planes airfield"),
    ("CATAIR", 8, "emergency airfield"),
    ("CATBRG", 1, "fixed bridge"),
    ("CATBRG", 2, "opening bridge"),
    ("CATBRG", 3, "swing bridge"),
    ("CATBRG", 4, "lifting bridge"),
    ("CATBRG", 5, "bascule bridge"),
    ("CATBRG", 6, "pontoon bridge"),
    ("CATBRG", 7, "draw bridge"),
    ("CATBRG", 8, "transporter bridge"),
    ("CATBRG", 9, "footbridge"),
    ("CATBRG", 10, "viaduct"),
    ("CATBRG", 11, "aqueduct"),
    ("CATBRG", 12, "suspension bridge"),
    ("CATBUA", 1, "urban area"),
    ("CATBUA", 2, "settlement"),
    ("CATBUA", 3, "village"),
    ("CATBUA", 4, "town"),
    ("CATBUA", 5, "city"),
    ("CATBUA", 6, "holiday village"),
    ("CATCAM", 1, "north cardinal mark"),
    ("CATCAM", 2, "east cardinal mark"),
    ("CATCAM", 3, "south cardinal mark"),
    ("CATCAM", 4, "west cardinal mark"),
    ("CATCAN", 1, "transportation"),
    ("CATCAN", 2, "drainage"),
    ("CATCAN", 3, "irrigation"),
    ("CATCBL", 1, "power line"),
    ("CATCBL", 2, "telephone/telegraph"),
    ("CATCBL", 3, "transmission line"),
    ("CATCBL", 4, "telephone"),
    ("CATCBL", 5, "telegraph"),
    ("CATCBL", 6, "mooring cable/chain"),
    ("CATCHP", 1, "custom"),
    ("CATCOA", 1, "steep coast"),
    ("CATCOA", 2, "flat coast"),
    ("CATCOA", 3, "sandy shore"),
    ("CATCOA", 4, "stony shore"),
    ("CATCOA", 5, "shingly shore"),
    ("CATCOA", 6, "glacier (seaward end)"),
    ("CATCOA", 7, "mangrove"),
    ("CATCOA", 8, "marshy shore"),
    ("CATCOA", 9, "coral reef"),
    ("CATCOA", 10, "ice coast"),
    ("CATCOA", 11, "shelly shore"),
    ("CATCON", 1, "aerial cableway (telepheric)"),
    ("CATCON", 2, "belt conveyor"),
    ("CATCOV", 1, "coverage available"),
    ("CATCOV", 2, "no coverage available"),
    ("CATCRN", 1, "crane without specific construction"),
    ("CATCRN", 2, "container crane/gantry"),
    ("CATCRN", 3, "sheerlegs"),
    ("CATCRN", 4, "travelling crane"),
    ("CATCRN", 5, "A-frame"),
    ("CATCTR", 1, "triangulation point"),
    ("CATCTR", 2, "observation spot"),
    ("CATCTR", 3, "fixed point"),
    ("CATCTR", 4, "bench-mark"),
    ("CATCTR", 5, "boundary mark"),
    ("CATCTR", 6, "horizontal control| main station"),
    ("CATCTR", 7, "horizontal control| secondary station"),
    ("CATDAM", 1, "weir"),
    ("CATDAM", 2, "dam"),
    ("CATDAM", 3, "flood barrage"),
    ("CATDIS", 1, "distance mark not physically installed"),
    ("CATDIS", 2, "visible mark pole"),
    ("CATDIS", 3, "visible mark board"),
    ("CATDIS", 4, "visible mark unknown shape"),
    ("CATDOC", 1, "tidal"),
    ("CATDOC", 2, "non-tidal (wet dock)"),
    ("CATDPG", 1, "general dumping ground"),
    ("CATDPG", 2, "chemical waste dumping ground"),
    ("CATDPG", 3, "nuclear waste dumping ground"),
    ("CATDPG", 4, "explosives dumping ground"),
    ("CATDPG", 5, "spoil ground"),
    ("CATDPG", 6, "vessel dumping ground"),
    ("CATFIF", 1, "fishing stake"),
    ("CATFIF", 2, "fish trap"),
    ("CATFIF", 3, "fish weir"),
    ("CATFIF", 4, "tunny net"),
    ("CATFNC", 1, "fence"),
    ("CATFNC", 2, "muir"),
    ("CATFNC", 3, "hedge"),
    ("CATFNC", 4, "wall"),
    ("CATFOG", 1, "explosive"),
    ("CATFOG", 2, "diaphone"),
    ("CATFOG", 3, "siren"),
    ("CATFOG", 4, "nautophone"),
    ("CATFOG", 5, "reed"),
    ("CATFOG", 6, "tyfon"),
    ("CATFOG", 7, "bell"),
    ("CATFOG", 8, "whistle"),
    ("CATFOG", 9, "gong"),
    ("CATFOG", 10, "horn"),
    ("CATFOR", 1, "castle"),
    ("CATFOR", 2, "fort"),
    ("CATFOR", 3, "battery"),
    ("CATFOR", 4, "blockhouse"),
    ("CATFOR", 5, "Martello tower"),
    ("CATFOR", 6, "redoubt"),
    ("CATFRY", 1, "'free moving' ferry"),
    ("CATFRY", 2, "cable ferry"),
    ("CATFRY", 3, "ice ferry"),
    ("CATGAT", 1, "gate in general"),
    ("CATGAT", 2, "flood barrage gate"),
    ("CATGAT", 3, "caisson"),
    ("CATGAT", 4, "lock gate"),
    ("CATGAT", 5, "dyke gate"),
    ("CATGAT", 6, "sluice"),
    ("CATHAF", 1, "RoRo-terminal"),
    ("CATHAF", 2, "timber yard"),
    ("CATHAF", 3, "ferry terminal"),
    ("CATHAF", 4, "fishing harbour"),
    ("CATHAF", 5, "yacht harbour/marina"),
    ("CATHAF", 6, "naval base"),
    ("CATHAF", 7, "tanker terminal"),
    ("CATHAF", 8, "passenger terminal"),
    ("CATHAF", 9, "shipyard"),
    ("CATHAF", 10, "container terminal"),
    ("CATHAF", 11, "bulk terminal"),
    ("CATHAF", 12, "syncrolift"),
    ("CATHAF", 13, "straddle carrier"),
    ("CATHLK", 1, "floating restaurant"),
    ("CATHLK", 2, "historic ship"),
    ("CATHLK", 3, "museum"),
    ("CATHLK", 4, "accommodation"),
    ("CATHLK", 5, "floating breakwater"),
    ("CATICE", 1, "fast ice"),
    ("CATICE", 2, "sea ice"),
    ("CATICE", 3, "growler area"),
    ("CATICE", 4, "pancake ice"),
    ("CATICE", 5, "glacier"),
    ("CATICE", 6, "ice peak"),
    ("CATICE", 7, "pack ice"),
    ("CATICE", 8, "polar ice"),
    ("CATLAM", 1, "port-hand lateral mark"),
    ("CATLAM", 2, "starboard-hand lateral mark"),
    ("CATLAM", 3, "preferred channel to starboard lateral mark"),
    ("CATLAM", 4, "preferred channel to port lateral mark"),
    ("CATLIT", 1, "directional function"),
    ("CATLIT", 2, "rear/upper light"),
    ("CATLIT", 3, "front/lower light"),
    ("CATLIT", 4, "leading light"),
    ("CATLIT", 5, "aero light"),
    ("CATLIT", 6, "air obstruction light"),
    ("CATLIT", 7, "fog detector light"),
    ("CATLIT", 8, "flood light"),
    ("CATLIT", 9, "strip light"),
    ("CATLIT", 10, "subsidiary light"),
    ("CATLIT", 11, "spotlight"),
    ("CATLIT", 12, "front"),
    ("CATLIT", 13, "rear"),
    ("CATLIT", 14, "lower"),
    ("CATLIT", 15, "upper"),
    ("CATLIT", 16, "moire effect"),
    ("CATLIT", 17, "emergency"),
    ("CATLIT", 18, "bearing light"),
    ("CATLIT", 19, "horizontally disposed"),
    ("CATLIT", 20, "vertically disposed"),
    ("CATLMK", 1, "cairn"),
    ("CATLMK", 2, "cemetery"),
    ("CATLMK", 3, "chimney"),
    ("CATLMK", 4, "dish aerial"),
    ("CATLMK", 5, "flagstaff (flagpole)"),
    ("CATLMK", 6, "flare stack"),
    ("CATLMK", 7, "mast"),
    ("CATLMK", 8, "windsock"),
    ("CATLMK", 9, "monument"),
    ("CATLMK", 10, "column (pillar)"),
    ("CATLMK", 11, "memorial plaque"),
    ("CATLMK", 12, "obelisk"),
    ("CATLMK", 13, "statue"),
    ("CATLMK", 14, "cross"),
    ("CATLMK", 15, "dome"),
    ("CATLMK", 16, "radar scanner"),
    ("CATLMK", 17, "tower"),
    ("CATLMK", 18, "windmill"),
    ("CATLMK", 19, "windmotor"),
    ("CATLMK", 20, "spire/minaret"),
    ("CATLMK", 21, "large rock or boulder on land"),
    ("CATLMK", 22, "large rock or boulder on land"),
    ("CATLND", 1, "fen"),
    ("CATLND", 2, "marsh"),
    ("CATLND", 3, "moor/bog"),
    ("CATLND", 4, "heathland"),
    ("CATLND", 5, "mountain range"),
    ("CATLND", 6, "lowlands"),
    ("CATLND", 7, "canyon lands"),
    ("CATLND", 8, "paddy field"),
    ("CATLND", 9, "agricultural land"),
    ("CATLND", 10, "savanna/grassland"),
    ("CATLND", 11, "parkland"),
    ("CATLND", 12, "swamp"),
    ("CATLND", 13, "landslide"),
    ("CATLND", 14, "lava flow"),
    ("CATLND", 15, "salt pan"),
    ("CATLND", 16, "moraine"),
    ("CATLND", 17, "crater"),
    ("CATLND", 18, "cave"),
    ("CATLND", 19, "rock column or pinnacle"),
    ("CATLND", 20, "cay"),
    ("CATMFA", 1, "crustaceans"),
    ("CATMFA", 2, "oysters/mussels"),
    ("CATMFA", 3, "fish"),
    ("CATMFA", 4, "seaweed"),
    ("CATMFA", 5, "pearl culture farm"),
    ("CATMOR", 1, "dolphin"),
    ("CATMOR", 2, "deviation dolphin"),
    ("CATMOR", 3, "bollard"),
    ("CATMOR", 4, "tie-up wall"),
    ("CATMOR", 5, "post or pile"),
    ("CATMOR", 6, "chain/wire/cable"),
    ("CATMOR", 7, "mooring buoy"),
    ("CATMPA", 1, "practice area in general"),
    ("CATMPA", 2, "torpedo exercise area"),
    ("CATMPA", 3, "submarine exercise area"),
    ("CATMPA", 4, "firing danger area"),
    ("CATMPA", 5, "mine-laying practice area"),
    ("CATMPA", 6, "small arms firing range"),
    ("CATNAV", 1, "clearing line"),
    ("CATNAV", 2, "transit line"),
    ("CATNAV", 3, "leading line bearing a recommended track"),
    ("CATOBS", 1, "snag/stump"),
    ("CATOBS", 2, "wellhead"),
    ("CATOBS", 3, "diffuser"),
    ("CATOBS", 4, "crib"),
    ("CATOBS", 5, "fish haven"),
    ("CATOBS", 6, "foul area"),
    ("CATOBS", 7, "foul ground"),
    ("CATOBS", 8, "ice boom"),
    ("CATOBS", 9, "ground tackle"),
    ("CATOBS", 10, "boom"),
    ("CATOFP", 1, "oil derrick/rig"),
    ("CATOFP", 2, "production platform"),
    ("CATOFP", 3, "observation/research platform"),
    ("CATOFP", 4, "articulated loading platform (ALP)"),
    ("CATOFP", 5, "single anchor leg mooring (SALM)"),
    ("CATOFP", 6, "mooring tower"),
    ("CATOFP", 7, "artificial island"),
    ("CATOFP", 8, "floating production| storage and off-loading vessel (FPSO)"),
    ("CATOFP", 9, "accommodation platform"),
    ("CATOFP", 10, "navigation| communication and control buoy (NCCB)"),
    ("CATOLB", 1, "oil retention (high pressure pipe)"),
    ("CATOLB", 2, "floating oil barrier"),
    ("CATPIL", 1, "boarding by pilot-cruising vessel"),
    ("CATPIL", 2, "boarding by helicopter"),
    ("CATPIL", 3, "pilot comes out from shore"),
    ("CATPIP", 2, "outfall pipe"),
    ("CATPIP", 3, "intake pipe"),
    ("CATPIP", 4, "sewer"),
    ("CATPIP", 5, "bubbler system"),
    ("CATPIP", 6, "supply pipe"),
    ("CATPLE", 1, "stake"),
    ("CATPLE", 2, "snag"),
    ("CATPLE", 3, "post"),
    ("CATPLE", 4, "tripodal"),
    ("CATPRA", 1, "quarry"),
    ("CATPRA", 2, "mine"),
    ("CATPRA", 3, "stockpile"),
    ("CATPRA", 4, "power station area"),
    ("CATPRA", 5, "refinery area"),
    ("CATPRA", 6, "timber yard"),
    ("CATPRA", 7, "factory area"),
    ("CATPRA", 8, "tank farm"),
    ("CATPRA", 9, "wind farm"),
    ("CATPRA", 10, "slag heap/spoil heap"),
    ("CATPYL", 1, "power transmission pylon/pole"),
    ("CATPYL", 2, "telephone/telegraph pylon/pole"),
    ("CATPYL", 3, "aerial cableway/sky pylon"),
    ("CATPYL", 4, "bridge pylon/tower"),
    ("CATPYL", 5, "bridge pier"),
    ("CATRAS", 1, "radar surveillance station"),
    ("CATREA", 1, "offshore safety zone"),
    ("CATREA", 2, "anchoring prohibition area"),
    ("CATREA", 3, "fishing prohibition area"),
    ("CATREA", 4, "nature reserve"),
    ("CATREA", 5, "bird sanctuary"),
    ("CATREA", 6, "game reserve"),
    ("CATREA", 7, "seal sanctuary"),
    ("CATREA", 8, "degaussing range"),
    ("CATREA", 9, "military area"),
    ("CATREA", 10, "historic wreck area"),
    ("CATREA", 11, "inshore traffic zone"),
    ("CATREA", 12, "navigational aid safety zone"),
    ("CATREA", 13, "danger of stranding area"),
    ("CATREA", 14, "minefield"),
    ("CATREA", 15, "diving prohibition area"),
    ("CATREA", 16, "area to be avoided"),
    ("CATREA", 17, "Prohibited area"),
    ("CATREA", 18, "swimming area"),
    ("CATREA", 19, "waiting area"),
    ("CATREA", 20, "research area"),
    ("CATREA", 21, "dredging area"),
    ("CATREA", 22, "fish sanctuary"),
    ("CATREA", 23, "ecological reserve"),
    ("CATREA", 24, "no wake area"),
    ("CATREA", 25, "swinging area"),
    ("CATREA", 26, "water skiing area"),
    ("CATROD", 1, "motorway"),
    ("CATROD", 2, "major road"),
    ("CATROD", 3, "minor road"),
    ("CATROD", 4, "track/path"),
    ("CATROD", 5, "major street"),
    ("CATROD", 6, "minor street"),
    ("CATROD", 7, "crossing"),
    ("CATROS", 1, "circular (non-directional) marine or| aero-marine radiobeacon"),
    ("CATROS", 2, "directional radiobeacon"),
    ("CATROS", 3, "rotating-pattern radiobeacon"),
    ("CATROS", 4, "Consol beacon"),
    ("CATROS", 5, "radio direction-finding station"),
    ("CATROS", 6, "coast radio station providing QTG service"),
    ("CATROS", 7, "aeronautical radiobeacon"),
    ("CATROS", 8, "Decca"),
    ("CATROS", 9, "Loran C"),
    ("CATROS", 10, "Differential GPS"),
    ("CATROS", 11, "Toran"),
    ("CATROS", 12, "Omega"),
    ("CATROS", 13, "Syledis"),
    ("CATROS", 14, "Chaika (Chayka)"),
    ("CATRSC", 1, "rescue station with lifeboat"),
    ("CATRSC", 2, "rescue station with rocket"),
    ("CATRSC", 3, "rescue station with lifeboat and rocket"),
    ("CATRSC", 4, "refuge for shipwrecked mariners"),
    ("CATRSC", 5, "refuge for intertidal area walkers"),
    ("CATRSC", 6, "lifeboat lying at a mooring"),
    ("CATRSC", 7, "aid radio station"),
    ("CATRSC", 8, "first aid equipment"),
    ("CATRTB", 1, "ramark| radar beacon transmitting continuously"),
    ("CATRTB", 2, "racon| radar transponder beacon"),
    ("CATRTB", 3, "leading racon/radar transponder beacon"),
    ("CATRUN", 1, "aeroplane runway"),
    ("CATRUN", 2, "helicopter landing pad"),
    ("CATSCF", 1, "visitor berth"),
    ("CATSCF", 2, "nautical club"),
    ("CATSCF", 3, "boat hoist"),
    ("CATSCF", 4, "sailmaker"),
    ("CATSCF", 5, "boatyard"),
    ("CATSCF", 6, "public inn"),
    ("CATSCF", 7, "restaurant"),
    ("CATSCF", 8, "chandler"),
    ("CATSCF", 9, "provisions"),
    ("CATSCF", 10, "doctor"),
    ("CATSCF", 11, "pharmacy"),
    ("CATSCF", 12, "water tap"),
    ("CATSCF", 13, "fuel station"),
    ("CATSCF", 14, "electricity"),
    ("CATSCF", 15, "bottle gas"),
    ("CATSCF", 16, "showers"),
    ("CATSCF", 17, "launderette"),
    ("CATSCF", 18, "public toilets"),
    ("CATSCF", 19, "post box"),
    ("CATSCF", 20, "public telephone"),
    ("CATSCF", 21, "refuse bin"),
    ("CATSCF", 22, "car park"),
    ("CATSCF", 23, "parking for boats and trailers"),
    ("CATSCF", 24, "caravan site"),
    ("CATSCF", 25, "camping site"),
    ("CATSCF", 26, "sewerage pump-out station"),
    ("CATSCF", 27, "emergency telephone"),
    ("CATSCF", 28, "landing/launching place for boats"),
    ("CATSCF", 29, "visitors mooring"),
    ("CATSCF", 30, "scrubbing berth"),
    ("CATSCF", 31, "picnic area"),
    ("CATSCF", 32, "mechanics workshop"),
    ("CATSCF", 33, "guard and/or security service"),
    ("CATSEA", 1, "sea area in general"),
    ("CATSEA", 2, "gat"),
    ("CATSEA", 3, "bank"),
    ("CATSEA", 4, "deep"),
    ("CATSEA", 5, "bay"),
    ("CATSEA", 6, "trench"),
    ("CATSEA", 7, "basin"),
    ("CATSEA", 8, "mud flats"),
    ("CATSEA", 9, "reef"),
    ("CATSEA", 10, "ledge"),
    ("CATSEA", 11, "canyon"),
    ("CATSEA", 12, "narrows"),
    ("CATSEA", 13, "shoal"),
    ("CATSEA", 14, "knoll"),
    ("CATSEA", 15, "ridge"),
    ("CATSEA", 16, "seamount"),
    ("CATSEA", 17, "pinnacle"),
    ("CATSEA", 18, "abyssal plain"),
    ("CATSEA", 19, "plateau"),
    ("CATSEA", 20, "spur"),
    ("CATSEA", 21, "shelf"),
    ("CATSEA", 22, "trough"),
    ("CATSEA", 23, "saddle"),
    ("CATSEA", 24, "abyssal hills"),
    ("CATSEA", 25, "apron"),
    ("CATSEA", 26, "archipelagic apron"),
    ("CATSEA", 27, "borderland"),
    ("CATSEA", 28, "continental margin"),
    ("CATSEA", 29, "continental rise"),
    ("CATSEA", 30, "escarpment"),
    ("CATSEA", 31, "fan"),
    ("CATSEA", 32, "fracture zone"),
    ("CATSEA", 33, "gap"),
    ("CATSEA", 34, "guyot"),
    ("CATSEA", 35, "hill"),
    ("CATSEA", 36, "hole"),
    ("CATSEA", 37, "levee"),
    ("CATSEA", 38, "median valley"),
    ("CATSEA", 39, "moat"),
    ("CATSEA", 40, "mountains"),
    ("CATSEA", 41, "peak"),
    ("CATSEA", 42, "province"),
    ("CATSEA", 43, "rise"),
    ("CATSEA", 44, "sea channel"),
    ("CATSEA", 45, "seamount chain"),
    ("CATSEA", 46, "shelf-edge"),
    ("CATSEA", 47, "sill"),
    ("CATSEA", 48, "slope"),
    ("CATSEA", 49, "terrace"),
    ("CATSEA", 50, "valley"),
    ("CATSEA", 51, "canal"),
    ("CATSEA", 52, "lake"),
    ("CATSEA", 53, "river"),
    ("CATSEA", 54, "reach"),
    ("CATSIL", 1, "silo in general"),
    ("CATSIL", 2, "tank in general"),
    ("CATSIL", 3, "grain elevator"),
    ("CATSIL", 4, "water tower"),
    ("CATSIT", 1, "port control"),
    ("CATSIT", 2, "port entry and departure"),
    ("CATSIT", 3, "International Port Traffic"),
    ("CATSIT", 4, "berthing"),
    ("CATSIT", 5, "dock"),
    ("CATSIT", 6, "lock"),
    ("CATSIT", 7, "flood barrage"),
    ("CATSIT", 8, "bridge passage"),
    ("CATSIT", 9, "dredging"),
    ("CATSIT", 10, "traffic control light"),
    ("CATSIW", 1, "danger"),
    ("CATSIW", 2, "maritime obstruction"),
    ("CATSIW", 3, "cable"),
    ("CATSIW", 4, "military practice"),
    ("CATSIW", 5, "distress"),
    ("CATSIW", 6, "weather"),
    ("CATSIW", 7, "storm"),
    ("CATSIW", 8, "ice"),
    ("CATSIW", 9, "time"),
    ("CATSIW", 10, "tide"),
    ("CATSIW", 11, "tidal stream"),
    ("CATSIW", 12, "tide gauge"),
    ("CATSIW", 13, "tide scale"),
    ("CATSIW", 14, "diving"),
    ("CATSIW", 15, "water level gauge"),
    ("CATSLC", 1, "breakwater"),
    ("CATSLC", 2, "groyne (groin)"),
    ("CATSLC", 3, "mole"),
    ("CATSLC", 4, "pier (jetty)"),
    ("CATSLC", 5, "promenade pier"),
    ("CATSLC", 6, "wharf (quay)"),
    ("CATSLC", 7, "training wall"),
    ("CATSLC", 8, "rip rap"),
    ("CATSLC", 9, "revetment"),
    ("CATSLC", 10, "sea wall"),
    ("CATSLC", 11, "landing steps"),
    ("CATSLC", 12, "ramp"),
    ("CATSLC", 13, "slipway"),
    ("CATSLC", 14, "fender"),
    ("CATSLC", 15, "solid face wharf"),
    ("CATSLC", 16, "open face wharf"),
    ("CATSLC", 17, "log ramp"),
    ("CATSLO", 1, "cutting"),
    ("CATSLO", 2, "embankment"),
    ("CATSLO", 3, "dune"),
    ("CATSLO", 4, "hill"),
    ("CATSLO", 5, "pingo"),
    ("CATSLO", 6, "cliff"),
    ("CATSLO", 7, "scree"),
    ("CATSPM", 1, "firing danger area mark"),
    ("CATSPM", 2, "target mark"),
    ("CATSPM", 3, "marker ship mark"),
    ("CATSPM", 4, "degaussing range mark"),
    ("CATSPM", 5, "barge mark"),
    ("CATSPM", 6, "cable mark"),
    ("CATSPM", 7, "spoil ground mark"),
    ("CATSPM", 8, "outfall mark"),
    ("CATSPM", 9, "ODAS (Ocean-Data-Acquisition-System)"),
    ("CATSPM", 10, "recording mark"),
    ("CATSPM", 11, "seaplane anchorage mark"),
    ("CATSPM", 12, "recreation zone mark"),
    ("CATSPM", 13, "private mark"),
    ("CATSPM", 14, "mooring mark"),
    ("CATSPM", 15, "LANBY (Large Automatic Navigational Buoy)"),
    ("CATSPM", 16, "leading mark"),
    ("CATSPM", 17, "measured distance mark"),
    ("CATSPM", 18, "notice mark"),
    ("CATSPM", 19, "TSS mark (Traffic Separation Scheme)"),
    ("CATSPM", 20, "anchoring prohibited mark"),
    ("CATSPM", 21, "berthing prohibited mark"),
    ("CATSPM", 22, "overtaking prohibited mark"),
    ("CATSPM", 23, "two-way traffic prohibited mark"),
    ("CATSPM", 24, "reduced wake mark"),
    ("CATSPM", 25, "speed limit mark"),
    ("CATSPM", 26, "stop mark"),
    ("CATSPM", 27, "general warning mark"),
    ("CATSPM", 28, "sound ship siren mark"),
    ("CATSPM", 29, "restricted vertical clearance mark"),
    ("CATSPM", 30, "maximum vessel draught mark"),
    ("CATSPM", 31, "restricted horizontal clearance mark"),
    ("CATSPM", 32, "strong current warning mark"),
    ("CATSPM", 33, "berthing permitted mark"),
    ("CATSPM", 34, "overhead power cable mark"),
    ("CATSPM", 35, "channel edge gradient mark"),
    ("CATSPM", 36, "telephone mark"),
    ("CATSPM", 37, "ferry crossing mark"),
    ("CATSPM", 38, "marine traffic lights"),
    ("CATSPM", 39, "pipeline mark"),
    ("CATSPM", 40, "anchorage mark"),
    ("CATSPM", 41, "clearing mark"),
    ("CATSPM", 42, "control mark"),
    ("CATSPM", 43, "diving mark"),
    ("CATSPM", 44, "refuge beacon"),
    ("CATSPM", 45, "foul ground mark"),
    ("CATSPM", 46, "yachting mark"),
    ("CATSPM", 47, "heliport mark"),
    ("CATSPM", 48, "GPS mark"),
    ("CATSPM", 49, "seaplane landing mark"),
    ("CATSPM", 50, "entry prohibited mark"),
    ("CATSPM", 51, "work in progress mark"),
    ("CATSPM", 52, "mark with unknown purpose"),
    ("CATSPM", 53, "wellhead mark"),
    ("CATSPM", 54, "channel separation mark"),
    ("CATSPM", 55, "marine farm mark"),
    ("CATSPM", 56, "artificial reef mark"),
    ("CATTRK", 1, "based on a system of fixed marks"),
    ("CATTRK", 2, "not based on a system of fixed marks"),
    ("CATTSS", 1, "IMO - adopted"),
    ("CATTSS", 2, "not IMO - adopted"),
    ("CATVEG", 1, "grass"),
    ("CATVEG", 2, "paddy field"),
    ("CATVEG", 3, "bush"),
    ("CATVEG", 4, "deciduous wood"),
    ("CATVEG", 5, "coniferous wood"),
    ("CATVEG", 6, "wood in general (inc mixed wood)"),
    ("CATVEG", 7, "mangroves"),
    ("CATVEG", 8, "park"),
    ("CATVEG", 9, "parkland"),
    ("CATVEG", 10, "mixed crops"),
    ("CATVEG", 11, "reed"),
    ("CATVEG", 12, "moss"),
    ("CATVEG", 13, "tree in general"),
    ("CATVEG", 14, "evergreen tree"),
    ("CATVEG", 15, "coniferous tree"),
    ("CATVEG", 16, "palm tree"),
    ("CATVEG", 17, "nipa palm tree"),
    ("CATVEG", 18, "casuarina tree"),
    ("CATVEG", 19, "eucalypt tree"),
    ("CATVEG", 20, "deciduous tree"),
    ("CATVEG", 21, "mangrove tree"),
    ("CATVEG", 22, "filao tree"),
    ("CATWAT", 1, "breakers"),
    ("CATWAT", 2, "eddies"),
    ("CATWAT", 3, "overfalls"),
    ("CATWAT", 4, "tide rips"),
    ("CATWAT", 5, "bombora"),
    ("CATWED", 1, "kelp"),
    ("CATWED", 2, "sea weed"),
    ("CATWED", 3, "sea grass"),
    ("CATWED", 4, "saragasso"),
    ("CATWRK", 1, "non-dangerous wreck"),
    ("CATWRK", 2, "dangerous wreck"),
    ("CATWRK", 3, "distributed remains of wreck"),
    ("CATWRK", 4, "wreck showing mast/masts"),
    ("CATWRK", 5, "wreck showing any portion of hull or superstructure"),
    ("CATZOC", 1, "zone of confidence A1"),
    ("CATZOC", 2, "zone of confidence A2"),
    ("CATZOC", 3, "zone of confidence B"),
    ("CATZOC", 4, "zone of confidence C"),
    ("CATZOC", 5, "zone of confidence D"),
    ("CATZOC", 6, "zone of confidence U (data not assessed)"),
    ("CAT_TS", 1, "flood stream"),
    ("CAT_TS", 2, "ebb stream"),
    ("CAT_TS", 3, "Other tidal flow"),
    ("COLOUR", 1, "white"),
    ("COLOUR", 2, "black"),
    ("COLOUR", 3, "red"),
    ("COLOUR", 4, "green"),
    ("COLOUR", 5, "blue"),
    ("COLOUR", 6, "yellow"),
    ("COLOUR", 7, "grey"),
    ("COLOUR", 8, "brown"),
    ("COLOUR", 9, "amber"),
    ("COLOUR", 10, "violet"),
    ("COLOUR", 11, "orange"),
    ("COLOUR", 12, "magenta"),
    ("COLOUR", 13, "pink"),
    ("COLPAT", 1, "horizontal stripes"),
    ("COLPAT", 2, "vertical stripes"),
    ("COLPAT", 3, "diagonal stripes"),
    ("COLPAT", 4, "squared"),
    ("COLPAT", 5, "stripes (direction unknown)"),
    ("COLPAT", 6, "border stripe"),
    ("CONRAD", 1, "radar conspicuous"),
    ("CONRAD", 2, "not radar conspicuous"),
    ("CONRAD", 3, "radar conspicuous (has radar reflector)"),
    ("CONVIS", 1, "visually conspicuous"),
    ("CONVIS", 2, "not visually conspicuous"),
    ("EXCLIT", 1, "light shown without change of character"),
    ("EXCLIT", 2, "daytime light"),
    ("EXCLIT", 3, "fog light"),
    ("EXCLIT", 4, "night light"),
    ("FUNCTN", 2, "harbour-master's office"),
    ("FUNCTN", 3, "custom office"),
    ("FUNCTN", 4, "health office"),
    ("FUNCTN", 5, "hospital"),
    ("FUNCTN", 6, "post office"),
    ("FUNCTN", 7, "hotel"),
    ("FUNCTN", 8, "railway station"),
    ("FUNCTN", 9, "police station"),
    ("FUNCTN", 10, "water-police station"),
    ("FUNCTN", 11, "pilot office"),
    ("FUNCTN", 12, "pilot lookout"),
    ("FUNCTN", 13, "bank office"),
    ("FUNCTN", 14, "headquarters for district control"),
    ("FUNCTN", 15, "transit shed/warehouse"),
    ("FUNCTN", 16, "factory"),
    ("FUNCTN", 17, "power station"),
    ("FUNCTN", 18, "administrative"),
    ("FUNCTN", 19, "educational facility"),
    ("FUNCTN", 20, "church"),
    ("FUNCTN", 21, "chapel"),
    ("FUNCTN", 22, "temple"),
    ("FUNCTN", 23, "pagoda"),
    ("FUNCTN", 24, "shinto shrine"),
    ("FUNCTN", 25, "buddhist temple"),
    ("FUNCTN", 26, "mosque"),
    ("FUNCTN", 27, "marabout"),
    ("FUNCTN", 28, "lookout"),
    ("FUNCTN", 29, "communication"),
    ("FUNCTN", 30, "television"),
    ("FUNCTN", 31, "radio"),
    ("FUNCTN", 32, "radar"),
    ("FUNCTN", 33, "light support"),
    ("FUNCTN", 34, "microwave"),
    ("FUNCTN", 35, "cooling"),
    ("FUNCTN", 36, "observation"),
    ("FUNCTN", 37, "time ball"),
    ("FUNCTN", 38, "clock"),
    ("FUNCTN", 39, "control"),
    ("FUNCTN", 40, "airship mooring"),
    ("FUNCTN", 41, "stadium"),
    ("FUNCTN", 42, "bus station"),
    ("JRSDTN", 1, "international"),
    ("JRSDTN", 2, "national"),
    ("JRSDTN", 3, "national sub-division"),
    ("LITCHR", 1, "fixed"),
    ("LITCHR", 2, "flashing"),
    ("LITCHR", 3, "long-flashing"),
    ("LITCHR", 4, "quick flashing"),
    ("LITCHR", 5, "very quick flashing"),
    ("LITCHR", 6, "ultra quick flashing"),
    ("LITCHR", 7, "isophased"),
    ("LITCHR", 8, "occulting"),
    ("LITCHR", 9, "interrupted quick flashing"),
    ("LITCHR", 10, "interrupted very quick flashing"),
    ("LITCHR", 11, "interrupted ultra-quick flashing"),
    ("LITCHR", 12, "morse"),
    ("LITCHR", 13, "fixed/flash"),
    ("LITCHR", 14, "flash/long-flash"),
    ("LITCHR", 15, "occulting"),
    ("LITCHR", 16, "fixed/long flash"),
    ("LITCHR", 17, "occulting"),
    ("LITCHR", 18, "long-flash"),
    ("LITCHR", 19, "flash"),
    ("LITCHR", 20, "group"),
    ("LITCHR", 25, "quick flash"),
    ("LITCHR", 26, "very quick flash"),
    ("LITCHR", 27, "ultra quick flash"),
    ("LITCHR", 28, "alternating"),
    ("LITCHR", 29, "fixed and alternating flashing"),
    ("LITVIS", 4, "intensified"),
    ("NATCON", 1, "masonry"),
    ("NATCON", 2, "concreted"),
    ("NATCON", 3, "loose boulders"),
    ("NATCON", 4, "hard surfaced"),
    ("NATCON", 5, "unsurfaced"),
    ("NATCON", 6, "wooden"),
    ("NATCON", 7, "metal"),
    ("NATCON", 8, "glass reinforced plastic"),
    ("NATCON", 9, "painted"),
    ("NATSUR", 9, "rock"),
    ("PRODCT", 1, "oil"),
    ("PRODCT", 2, "gas"),
    ("PRODCT", 3, "water"),
    ("PRODCT", 4, "stone"),
    ("PRODCT", 5, "coal"),
    ("PRODCT", 6, "ore"),
    ("PRODCT", 7, "chemicals"),
    ("PRODCT", 8, "drinking water"),
    ("PRODCT", 9, "milk"),
    ("PRODCT", 10, "bauxite"),
    ("PRODCT", 11, "coke"),
    ("PRODCT", 12, "iron ingots"),
    ("PRODCT", 13, "salt"),
    ("PRODCT", 14, "sand"),
    ("PRODCT", 15, "timber"),
    ("PRODCT", 16, "sawdust/woodchips"),
    ("PRODCT", 17, "scrap metal"),
    ("PRODCT", 18, "liquified natural gas"),
    ("PRODCT", 19, "liquified petroleum gas"),
    ("PRODCT", 20, "wine"),
    ("PRODCT", 21, "cement"),
    ("PRODCT", 22, "grain"),
    ("QUAPOS", 4, "approximate"),
    ("QUAPOS", 10, "precisely known"),
    ("QUASOU", 1, "depth known"),
    ("QUASOU", 2, "depth unknown"),
    ("QUASOU", 3, "doubtful sounding"),
    ("QUASOU", 4, "unreliable sounding"),
    ("QUASOU", 5, "no bottom found at value shown"),
    ("QUASOU", 6, "least depth known"),
    ("QUASOU", 7, "least depth unknown - safe clearance at value shown"),
    ("QUASOU", 8, "value reported (not surveyed)"),
    ("QUASOU", 9, "value reported (not confirmed)"),
    ("QUASOU", 10, "maintained depth"),
    ("QUASOU", 11, "not regularly maintained"),
    ("RESTRN", 1, "anchoring prohibited"),
    ("RESTRN", 2, "anchoring restricted"),
    ("RESTRN", 3, "fishing prohibited"),
    ("RESTRN", 4, "fishing restricted"),
    ("RESTRN", 5, "trawling prohibited"),
    ("RESTRN", 6, "trawling restricted"),
    ("RESTRN", 7, "entry prohibited"),
    ("RESTRN", 8, "entry restricted"),
    ("RESTRN", 9, "dredging prohibited"),
    ("RESTRN", 10, "dredging restricted"),
    ("RESTRN", 11, "diving prohibited"),
    ("RESTRN", 12, "diving restricted"),
    ("RESTRN", 13, "no wake"),
    ("RESTRN", 14, "area to be avoided"),
    ("RESTRN", 15, "construction prohibited"),
    ("RESTRN", 16, "discharging prohibited"),
    ("RESTRN", 17, "discharging restricted"),
    ("RESTRN", 18, "industrial or mineral exploration/development prohibited"),
    ("RESTRN", 19, "industrial or mineral exploration/development restricted"),
    ("RESTRN", 20, "drilling prohibited"),
    ("RESTRN", 21, "drilling rstricted"),
    ("RESTRN", 22, "removal of historical artifacts prohibited"),
    ("RESTRN", 23, "cargo transshipment (lightering) prohibited"),
    ("RESTRN", 24, "dragging prohibted"),
    ("RESTRN", 25, "stopping prohibited"),
    ("RESTRN", 26, "landing prohibited"),
    ("RESTRN", 27, "speed restricted"),
    ("SIGGEN", 1, "automatically"),
    ("SIGGEN", 2, "by wave action"),
    ("STATUS", 2, "occasional"),
    ("STATUS", 3, "recommended"),
    ("STATUS", 4, "not in use"),
    ("STATUS", 8, "private"),
    ("STATUS", 9, "mandatory"),
    ("STATUS", 12, "illuminated"),
    ("STATUS", 14, "public"),
    ("STATUS", 16, "watched"),
    ("STATUS", 17, "un-watched"),
    ("SURTYP", 2, "controlled survey"),
    ("TECSOU", 1, "found by echo-sounder"),
    ("TECSOU", 2, "found by side-scan-sonar"),
    ("TECSOU", 3, "found by multi-beam"),
    ("TECSOU", 4, "found by diver"),
    ("TECSOU", 5, "found by lead-line"),
    ("TECSOU", 6, "swept by wire-drag"),
    ("TECSOU", 7, "found by laser"),
    ("TECSOU", 8, "swept by vertical acoustic system"),
    ("TECSOU", 9, "found by electromagnetic sensor"),
    ("TECSOU", 10, "photogrammetry"),
    ("TECSOU", 11, "satellite imagery"),
    ("TECSOU", 12, "found by levelling"),
    ("TECSOU", 13, "swept by side-scan-sonar"),
    ("TECSOU", 14, "computer generated"),
    ("TOPSHP", 1, "cone. point up"),
    ("TOPSHP", 2, "cone. point down"),
    ("TOPSHP", 3, "sphere"),
    ("TOPSHP", 4, "2 spheres"),
    ("TOPSHP", 5, "cylinder (can)"),
    ("TOPSHP", 6, "board"),
    ("TOPSHP", 7, "x-shape (St. Andrew's cross)"),
    ("TOPSHP", 8, "upright cross (St George's cross)"),
    ("TOPSHP", 9, "cube. point up"),
    ("TOPSHP", 10, "2 cones. point to point"),
    ("TOPSHP", 11, "2 cones. base to base"),
    ("TOPSHP", 12, "rhombus"),
    ("TOPSHP", 13, "2 cones (points upward)"),
    ("TOPSHP", 14, "2 cones (points downward)"),
    ("TOPSHP", 15, "besom. point up (broom or perch)"),
    ("TOPSHP", 16, "besom. point down (broom or perch)"),
    ("TOPSHP", 17, "flag"),
    ("TOPSHP", 18, "sphere over rhombus"),
    ("TOPSHP", 19, "square"),
    ("TOPSHP", 20, "rectangle. horizontal"),
    ("TOPSHP", 21, "rectangle. vertical"),
    ("TOPSHP", 22, "trapezium. up"),
    ("TOPSHP", 23, "trapezium. down"),
    ("TOPSHP", 24, "triangle point up"),
    ("TOPSHP", 25, "triangle. point down"),
    ("TOPSHP", 26, "circle"),
    ("TOPSHP", 27, "two upright crosses (one over the other)"),
    ("TOPSHP", 28, "T-shape"),
    ("TOPSHP", 29, "triangle pointing up over a circle"),
    ("TOPSHP", 30, "upright cross over a circle"),
    ("TOPSHP", 31, "rhombus over a circle"),
    ("TOPSHP", 32, "circle over a triangle pointing up"),
    ("TOPSHP", 33, "other shape (see INFORM)"),
    ("TRAFIC", 1, "inbound"),
    ("TRAFIC", 2, "outbbound"),
    ("TRAFIC", 3, "one-way"),
    ("TRAFIC", 4, "two-way"),
    ("WATLEV", 1, "partly submerged at high water"),
    ("WATLEV", 2, "always dry"),
    ("WATLEV", 3, "always under water/submerged"),
    ("WATLEV", 4, "covers and uncovers"),
    ("WATLEV", 5, "awash"),
    ("WATLEV", 6, "subject to inundation or flooding"),
    ("WATLEV", 7, "floating"),
    ("addmrk", 1, "top (board)"),
    ("addmrk", 2, "bottom (board)"),
    ("addmrk", 3, "right (triangle to the right)"),
    ("addmrk", 4, "left (triangle to the left)"),
    ("addmrk", 5, "bottom (triangle to the bottom)"),
    ("bunves", 1, "bunker vessel available"),
    ("bunves", 2, "no bunker vessel available"),
    ("catach", 1, "unrestricted anchorage"),
    ("catach", 2, "deep water anchorage"),
    ("catach", 3, "tanker anchorage"),
    ("catach", 4, "explosives anchorage"),
    ("catach", 5, "quarantine anchorage"),
    ("catach", 6, "sea-plane anchorage"),
    ("catach", 7, "small craft anchorage"),
    ("catach", 9, "anchorage for periods up to 24 hours"),
    ("catach", 10, "anchorage for pushing-navigation vessels"),
    ("catach", 11, "anchorage for other vessels than pushing-navigation vessels"),
    ("catbrt", 1, "loading"),
    ("catbrt", 2, "unloading"),
    ("catbrt", 3, "overnight accommodation"),
    ("catbrt", 4, "berth for pushing-navigation vessels"),
    ("catbrt", 5, "berth for other vessels than pushing-navigation vessels"),
    ("catbrt", 6, "fleeting area"),
    ("catbrt", 7, "first class landing"),
    ("catbrt", 8, "second class landing"),
    ("catbun", 1, "diesel oil"),
    ("catbun", 2, "water"),
    ("catbun", 3, "ballast"),
    ("catcbl", 1, "power line"),
    ("catcbl", 3, "transmission line"),
    ("catcbl", 4, "telephone"),
    ("catcbl", 5, "telegraph"),
    ("catcbl", 6, "mooring cable/chain"),
    ("catcbl", 7, "ferry cable"),
    ("catccl", 1, "0 small vessels and pleasure craft"),
    ("catccl", 2, "I peniche"),
    ("catccl", 3, "II campine barge"),
    ("catccl", 4, "III Dortmund-Ems barge"),
    ("catccl", 5, "IV Rhine-Herne barge"),
    ("catccl", 6, "Va Large Rhine barge. 1-barge push-tow unit"),
    ("catccl", 7, "Vb 2-barge push-tow unit. long formation"),
    ("catccl", 8, "VIa 2-barge push-tow unit. wide formation"),
    ("catccl", 9, "VIb 4-barge push-tow unit"),
    ("catccl", 10, "VIc 6-barge push-tow unit"),
    ("catccl", 11, "No CEMT class"),
    ("catchp", 1, "custom"),
    ("catchp", 2, "border"),
    ("catcom", 1, "VTS centre"),
    ("catcom", 2, "VTS sector"),
    ("catcom", 3, "IVS point"),
    ("catcom", 4, "MID"),
    ("catcom", 5, "lock"),
    ("catcom", 6, "bridge"),
    ("catcom", 7, "custom"),
    ("catcom", 8, "harbour"),
    ("catexs", 1, "Lift-Lock"),
    ("catexs", 2, "Aqueduct"),
    ("catexs", 3, "Sloping plane lock"),
    ("catexs", 4, "Water slope lock (Pente d'Eau)"),
    ("catexs", 5, "Other"),
    ("catfry", 4, "swinging wire ferry"),
    ("catgag", 1, "water level staff / pole"),
    ("catgag", 2, "recording water level gauge"),
    ("catgag", 3, "recording water level gauge with remote access"),
    ("catgag", 4, "recording water level gauge with external indicator"),
    ("catgag", 5, "recording water level gauge with remote access and remote indicator"),
    ("cathaf", 1, "RoRo-terminal"),
    ("cathaf", 3, "ferry terminal"),
    ("cathaf", 4, "fishing harbour"),
    ("cathaf", 6, "naval base"),
    ("cathaf", 7, "tanker terminal"),
    ("cathaf", 8, "passenger terminal"),
    ("cathaf", 9, "shipyard"),
    ("cathaf", 10, "container terminal"),
    ("cathaf", 11, "bulk terminal"),
    ("cathaf", 12, "syncrolift"),
    ("cathaf", 13, "straddle carrier"),
    ("cathaf", 16, "service and repair"),
    ("cathaf", 17, "quarantine station"),
    ("cathbr", 1, "custom harbour"),
    ("cathbr", 2, "port of refuge"),
    ("cathbr", 3, "yacht harbour/marina"),
    ("cathbr", 4, "fishing harbour"),
    ("cathbr", 5, "private harbour"),
    ("cathlk", 1, "floating restaurant"),
    ("cathlk", 2, "historic ship"),
    ("cathlk", 3, "museum"),
    ("cathlk", 4, "accommodation"),
    ("cathlk", 5, "floating breakwater"),
    ("cathlk", 6, "casino boat"),
    ("catlam", 1, "port-hand lateral mark"),
    ("catlam", 2, "starboard-hand lateral mark"),
    ("catlam", 3, "preferred channel to starboard lateral mark"),
    ("catlam", 4, "preferred channel to port lateral mark"),
    ("catlam", 5, "right-hand side of the waterway"),
    ("catlam", 6, "left-hand side of the waterway"),
    ("catlam", 7, "right-hand side of the channel"),
    ("catlam", 8, "left-hand side of the channel"),
    ("catlam", 9, "bifurcation of the waterway"),
    ("catlam", 10, "bifurcation of the channel"),
    ("catlam", 11, "channel near the right bank"),
    ("catlam", 12, "channel near the left bank"),
    ("catlam", 13, "channel cross-over to the right bank"),
    ("catlam", 14, "channel cross-over to the left bank"),
    ("catlam", 15, "danger point or obstacles at the right-hand side"),
    ("catlam", 16, "obstruction at the left-hand side"),
    ("catlam", 17, "turn off at the right-hand side"),
    ("catlam", 18, "turn off at the left-hand side"),
    ("catlam", 19, "junction at the right-hand side"),
    ("catlam", 20, "junction at the left-hand side"),
    ("catlam", 21, "harbour entry at the right-hand side"),
    ("catlam", 22, "harbour entry at the left-hand side"),
    ("catlam", 23, "bridge pier mark"),
    ("catnmk", 1, "(A.1) no entry"),
    ("catnmk", 2, "(A.1a) closed area. but small craft boats without engine permitted (only RheinSchPV and Binnenvaatpolitiereglement)"),
    ("catnmk", 3, "(A.2) no overtaking"),
    ("catnmk", 4, "(A.3) no overtaking of convoys by convoys"),
    ("catnmk", 5, "(A.4) no passing or overtaking"),
    ("catnmk", 6, "(A.5) no berthing (i.e. no anchoring or making fast to the bank)"),
    ("catnmk", 7, "(A.5.1) no berthing within the breadth indicated in meters(measured from the sign)"),
    ("catnmk", 8, "(A.6) no anchoring or trailing of anchors. cables or chains"),
    ("catnmk", 9, "(A.7) no making fast to the bank"),
    ("catnmk", 10, "(A.8) no turning"),
    ("catnmk", 11, "(A.9) Do not create wash"),
    ("catnmk", 12, "(A.10) no passing on left side (in openings of bridges or weirs)"),
    ("catnmk", 13, "(A.10) no passing on right side (in openings of bridges or weirs)"),
    ("catnmk", 14, "(A.12) motorized craft prohibited"),
    ("catnmk", 15, "(A.13) all sports and pleasure craft prohibited"),
    ("catnmk", 16, "(A.14) water skiing prohibited"),
    ("catnmk", 17, "(A.15) sailing vessels prohibited"),
    ("catnmk", 18, "(A.16) all craft other than motorized vessels or sailing craft prohibited"),
    ("catnmk", 19, "(A.17) use of sailboards prohibited"),
    ("catnmk", 20, "(A.20) water bikes prohibited"),
    ("catnmk", 21, "(A.18) end of zone authorized for high speed navigation of small sport and pleasure craft prohibited"),
    ("catnmk", 22, "(A.19) no launching or beaching of vessels"),
    ("catnmk", 23, "(B.1) proceed in left direction"),
    ("catnmk", 24, "(B.1) proceed in right direction"),
    ("catnmk", 25, "(B.2a) move to the side of the channel on your port side"),
    ("catnmk", 26, "(B.2b) move to the side of the channel on your starboard side"),
    ("catnmk", 27, "(B.3a) keep on the side of the channel on your portside"),
    ("catnmk", 28, "(B.3b) keep on the side of the channel on your starboard side"),
    ("catnmk", 29, "(B.4a) cross channel to port"),
    ("catnmk", 30, "(B.4b) cross channel to starboard"),
    ("catnmk", 31, "(B.5) stop as prescribed in the regulations"),
    ("catnmk", 32, "(B.6) do not exceed the speed indicated (in km/h)"),
    ("catnmk", 33, "(B.7) give a sound signal"),
    ("catnmk", 34, "(B.8) keep a particulary sharp lookout"),
    ("catnmk", 35, "(B.9a) do not enter the main waterway until certain that this will not oblige vessels proceeding on it to change their course or speed"),
    ("catnmk", 36, "(B.9b) do not cross the main waterway until certain that this will not oblige vessels proceeding on it to change their course or speed"),
    ("catnmk", 37, "(B.11) obligation to enter into a radiotelephone link on the channel as indicated on the board"),
    ("catnmk", 38, "(C.1) depth of water limited"),
    ("catnmk", 39, "(C.2) headroom limited"),
    ("catnmk", 40, "(C.3) width of passage or channel limited"),
    ("catnmk", 41, "(C.4) there are restrictions on navigation: make inquiries (with additional sign at bottom of main sign)"),
    ("catnmk", 42, "(C.5) the channel lies at a distance from the left bank"),
    ("catnmk", 43, "(C.5) the channel lies at a distance from the right bank"),
    ("catnmk", 44, "(D.1a) recommended channel in both directions"),
    ("catnmk", 45, "(D.1b) recommended channel only in the direction indicated. passage in the opposite direction prohibited (at bridges)"),
    ("catnmk", 46, "(D.2) you are recommended to keep on right side (in openings of bridges and weirs)"),
    ("catnmk", 47, "(D.2) you are recommended to keep on left side (in openings of bridges and weirs)"),
    ("catnmk", 48, "(D.3) you are recommended to proceed in the left direction"),
    ("catnmk", 49, "(D.3) you are recommended to proceed in the right direction"),
    ("catnmk", 50, "(E.1) entry permitted (general sign)"),
    ("catnmk", 51, "(E.2) overhead cable crossing"),
    ("catnmk", 52, "(E.3) weir"),
    ("catnmk", 53, "(E.4a) ferry-boat not moving independently"),
    ("catnmk", 54, "(E.4b) ferry-boat moving independently"),
    ("catnmk", 55, "(E.5) berthing (i.e. no anchoring or making fast to the bank) permitted"),
    ("catnmk", 56, "(E.5.1) berthing permitted on the stretch of water of the breadth measured from. and shown on the board in meters"),
    ("catnmk", 57, "(E.5.2) berthing permitted on the stretch of water bounded by the distances measured from. and shown on the board in meters"),
    ("catnmk", 58, "(E.5.3) maximum number of vessels permitted to berth abreast"),
    ("catnmk", 59, "(E.5.4) berthing area reserved for pushing-navigation vessels that are not required to carry blue lights or blue cones"),
    ("catnmk", 60, "(E.5.5) berthing area reserved for pushing-navigation vessels that are required to carry one blue light or one blue cone"),
    ("catnmk", 61, "(E.5.6) berthing area reserved for pushing-navigation vessels that are required to carry two blue lights or two blue cones"),
    ("catnmk", 62, "(E.5.7) berthing area reserved for pushing-navigation vessels that are required to carry three blue lights or three blue cones"),
    ("catnmk", 63, "(E.5.8) berthing area reserved for vessels other than pushing-navigation vessels that are not required to carry blue lights or blue cones"),
    ("catnmk", 64, "(E.5.9) berthing area reserved for vessels other than for pushing-navigation vessels that are required to carry one blue light or one blue cone"),
    ("catnmk", 65, "(E.5.10) berthing area reserved for vessels other than for pushing-navigation vessels that are required to carry two blue lights or two blue cones"),
    ("catnmk", 66, "(E.5.11) berthing area reserved for vessels other than for pushing-navigation vessels that are required to carry three blue lights or three blue cones"),
    ("catnmk", 67, "(E.5.12) berthing area reserved for all vessels that are not required to carry blue lights or blue cones"),
    ("catnmk", 68, "(E.5.13) berthing area reserved for all vessels that are required to carry one blue light or one blue cone"),
    ("catnmk", 69, "(E.5.14) berthing area reserved for all vessels that are required to carry two blue lights or two blue cones"),
    ("catnmk", 70, "(E.5.15) berthing area reserved for all vessels that are required to carry three blue lights or three blue cones"),
    ("catnmk", 71, "(E.6) anchoring or trailing of anchors. cables or chains permitted"),
    ("catnmk", 72, "(E.7) making fast to the bank permitted"),
    ("catnmk", 73, "(E.7.1) berthing area reserved for loading and unloading of vehicles"),
    ("catnmk", 74, "(E.8) turning area"),
    ("catnmk", 75, "(E.9a) crossing with secondary waterway ahead"),
    ("catnmk", 76, "(E.9b) secondary waterway ahead on the right"),
    ("catnmk", 77, "(E.9c) secondary waterway ahead on the left"),
    ("catnmk", 78, "(E.9d) secondary waterway ahead. main waterway on the right"),
    ("catnmk", 79, "(E.9e) secondary waterway ahead. main waterwar on the left"),
    ("catnmk", 80, "(E.9f) secondary waterway on the left. main waterway on the right"),
    ("catnmk", 81, "(E.9g) secondary waterway on the right. main waterway on the left"),
    ("catnmk", 82, "(E.9h) secondary waterway ahead and on the left. main waterway on the right"),
    ("catnmk", 83, "(E.9i) secondary waterway ahead and on the right. main waterway on the left"),
    ("catnmk", 84, "(E.10a) crossing with main waterway ahead"),
    ("catnmk", 85, "(E.10b) main waterway ahead"),
    ("catnmk", 86, "(E.10c) junction with main waterway ahead and right"),
    ("catnmk", 87, "(E.10d) junction with main waterway ahead and left"),
    ("catnmk", 88, "(E.10e) junction with main waterway ahead and right. secondary waterway on the left"),
    ("catnmk", 89, "(E.10f) junction with main waterway ahead and left. secondary waterway on the right"),
    ("catnmk", 90, "(E.11) end of prohibition or obligation applying to traffic in one direction only. or end of a restriction"),
    ("catnmk", 91, "(E.13) drinking water supply"),
    ("catnmk", 92, "(E.14) telephone"),
    ("catnmk", 93, "(E.15) motorized vessels  permitted"),
    ("catnmk", 94, "(E.16) sport and pleasure craft permitted"),
    ("catnmk", 95, "(E.17) water skiing permitted"),
    ("catnmk", 96, "(E.18) sailing vessels permitted"),
    ("catnmk", 97, "(E.19) craft other than motorized vessels or sailing craft permitted"),
    ("catnmk", 98, "(E.20) use of sailboards permitted"),
    ("catnmk", 99, "(E.23) possibility of obtaining nautical information by radiotelephone on the channel indicated"),
    ("catnmk", 100, "(E.24) water bikes permitted"),
    ("catnmk", 101, "(E.21) zone authorized for high speed navigation of small sport and pleasure"),
    ("catnmk", 102, "(E.22) launching or beaching of vessels permitted"),
    ("catrfd", 1, "cargo residue/slop"),
    ("catrfd", 2, "waste oil"),
    ("catrfd", 3, "grey/black water"),
    ("catrfd", 4, "domestic refuse"),
    ("catsit", 2, "port entry and departure"),
    ("catsit", 6, "lock"),
    ("catsit", 8, "bridge passage"),
    ("catsit", 10, "oncomig traffic indication"),
    ("catsiw", 15, "high water mark"),
    ("catsiw", 16, "vertical clearance indication"),
    ("catsiw", 18, "depth indication"),
    ("catslc", 7, "training wall"),
    ("catslc", 18, "lock/guide wall"),
    ("cattab", 1, "operational period"),
    ("cattab", 2, "non-operational period"),
    ("catvtr", 1, "official"),
    ("catvtr", 2, "private"),
    ("catvtr", 3, "suitable for car cranes"),
    ("catvtr", 4, "suitable for car planks"),
    ("catvtr", 5, "permission required"),
    ("catvtr", 6, "locked gate"),
    ("clsdng", 1, "one blue light / cone"),
    ("clsdng", 2, "two blue lights / cones"),
    ("clsdng", 3, "three blue lights / cones"),
    ("clsdng", 4, "no blue light / cone"),
    ("dirimp", 1, "upstream"),
    ("dirimp", 2, "downstream"),
    ("dirimp", 3, "to the left bank"),
    ("dirimp", 4, "to the right bank"),
    ("fnctnm", 1, "prohibition mark"),
    ("fnctnm", 2, "regulation mark"),
    ("fnctnm", 3, "restriction mark"),
    ("fnctnm", 4, "recommendation mark"),
    ("fnctnm", 5, "information mark"),
    ("hunits", 1, "metres"),
    ("hunits", 2, "feet"),
    ("hunits", 3, "kilometres"),
    ("hunits", 4, "hectometres"),
    ("hunits", 5, "statute miles"),
    ("hunits", 6, "nautical miles"),
    ("lc_ase", 1, "all types"),
    ("lc_ase", 2, "other"),
    ("lc_ase", 3, "single vessel"),
    ("lc_ase", 5, "convoy"),
    ("lc_ase", 6, "formation"),
    ("lc_ase", 7, "rigid convoy"),
    ("lc_ase", 8, "pushed convoy"),
    ("lc_ase", 9, "breasted up formation"),
    ("lc_ase", 10, "towed convoy"),
    ("lc_asi", 1, "all types"),
    ("lc_asi", 2, "other"),
    ("lc_asi", 3, "single vessel"),
    ("lc_asi", 5, "convoy"),
    ("lc_asi", 6, "formation"),
    ("lc_asi", 7, "rigid convoy"),
    ("lc_asi", 8, "pushed convoy"),
    ("lc_asi", 9, "breasted up formation"),
    ("lc_asi", 10, "towed convoy"),
    ("lc_cce", 1, "all types"),
    ("lc_cce", 2, "other"),
    ("lc_cce", 4, "bulk"),
    ("lc_cce", 5, "dry cargo"),
    ("lc_cce", 6, "liquid cargo"),
    ("lc_cce", 7, "liquid cargo (type N)"),
    ("lc_cce", 8, "liquid cargo (type C)"),
    ("lc_cce", 9, "gas"),
    ("lc_cci", 1, "all types"),
    ("lc_cci", 2, "other"),
    ("lc_cci", 4, "bulk"),
    ("lc_cci", 5, "dry cargo"),
    ("lc_cci", 6, "liquid cargo"),
    ("lc_cci", 7, "liquid cargo (type N)"),
    ("lc_cci", 8, "liquid cargo (type C)"),
    ("lc_cci", 9, "gas"),
    ("lc_cse", 1, "all types"),
    ("lc_cse", 2, "other"),
    ("lc_cse", 3, "non-motorized vessel"),
    ("lc_cse", 5, "craft"),
    ("lc_cse", 6, "vessel"),
    ("lc_cse", 7, "inland waterway vessel"),
    ("lc_cse", 8, "sea going ship"),
    ("lc_cse", 9, "motor vessel"),
    ("lc_cse", 10, "motor tanker"),
    ("lc_cse", 11, "motor cargo vessel"),
    ("lc_cse", 12, "canal barge"),
    ("lc_cse", 13, "tug"),
    ("lc_cse", 14, "pusher"),
    ("lc_cse", 15, "barge"),
    ("lc_cse", 16, "tank barge"),
    ("lc_cse", 17, "dumb barge"),
    ("lc_cse", 18, "lighter"),
    ("lc_cse", 19, "tank lighter"),
    ("lc_cse", 20, "cargo lighter"),
    ("lc_cse", 21, "ship borne lighter"),
    ("lc_cse", 22, "passenger vessel"),
    ("lc_cse", 23, "passenger sailing vessel"),
    ("lc_cse", 24, "day trip vessel"),
    ("lc_cse", 25, "cabin vessel"),
    ("lc_cse", 26, "High-speed vessel"),
    ("lc_cse", 27, "floating equipment"),
    ("lc_cse", 28, "worksite craft"),
    ("lc_cse", 29, "recreational craft"),
    ("lc_cse", 30, "Dinghy"),
    ("lc_cse", 31, "floating establishment"),
    ("lc_cse", 32, "floating  object"),
    ("lc_csi", 1, "all types"),
    ("lc_csi", 2, "other"),
    ("lc_csi", 3, "non-motorized vessel"),
    ("lc_csi", 5, "craft"),
    ("lc_csi", 6, "vessel"),
    ("lc_csi", 7, "inland waterway vessel"),
    ("lc_csi", 8, "sea going ship"),
    ("lc_csi", 9, "motor vessel"),
    ("lc_csi", 10, "motor tanker"),
    ("lc_csi", 11, "motor cargo vessel"),
    ("lc_csi", 12, "canal barge"),
    ("lc_csi", 13, "tug"),
    ("lc_csi", 14, "pusher"),
    ("lc_csi", 15, "barge"),
    ("lc_csi", 16, "tank barge"),
    ("lc_csi", 17, "dumb barge"),
    ("lc_csi", 18, "lighter"),
    ("lc_csi", 19, "tank lighter"),
    ("lc_csi", 20, "cargo lighter"),
    ("lc_csi", 21, "ship borne lighter"),
    ("lc_csi", 22, "passenger vessel"),
    ("lc_csi", 23, "passenger sailing vessel"),
    ("lc_csi", 24, "day trip vessel"),
    ("lc_csi", 25, "cabin vessel"),
    ("lc_csi", 26, "High-speed vessel"),
    ("lc_csi", 27, "floating equipment"),
    ("lc_csi", 28, "worksite craft"),
    ("lc_csi", 29, "recreational craft"),
    ("lc_csi", 30, "Dinghy"),
    ("lc_csi", 31, "floating establishment"),
    ("lc_csi", 32, "floating  object"),
    ("lg_fnc", 1, "other"),
    ("lg_fnc", 2, "prohibited"),
    ("lg_fnc", 3, "prohibited. with exceptions"),
    ("lg_fnc", 4, "permitted"),
    ("lg_fnc", 5, "permitted. with exceptions"),
    ("lg_fnc", 6, "recommended"),
    ("lg_fnc", 7, "not recommended"),
    ("lg_rel", 1, "other"),
    ("lg_rel", 2, "usage of waterway"),
    ("lg_rel", 3, "carriage of equipment"),
    ("lg_rel", 4, "task.operation"),
    ("lg_spr", 1, "other"),
    ("lg_spr", 2, "speed over ground"),
    ("lg_spr", 3, "speed through water"),
    ("lg_wdu", 1, "other"),
    ("lg_wdu", 2, "cubic meters"),
    ("lg_wdu", 3, "tonnes"),
    ("marsys", 1, "IALA A"),
    ("marsys", 2, "IALA B"),
    ("marsys", 9, "no system"),
    ("marsys", 10, "other sytem"),
    ("marsys", 11, "CEVNI"),
    ("marsys", 12, "Russian inland waterway regulations"),
    ("reflev", 1, "Baltic datum"),
    ("reflev", 2, "Adriatic level"),
    ("reflev", 3, "Amsterdam Ordnance Datum (NAP)"),
    ("reflev", 4, "Mean Sea Level"),
    ("reflev", 5, "Other datum"),
    ("reflev", 6, "National Geodetic Vertical Datum - NGVD29"),
    ("reflev", 7, "North American Vertical Datum - NAVD88"),
    ("reflev", 8, "Mean sea level 1912"),
    ("reflev", 9, "Mean sea level 1929"),
    ("restrn", 1, "anchoring prohibited"),
    ("restrn", 2, "anchoring restricted"),
    ("restrn", 7, "entry prohibited"),
    ("restrn", 8, "entry restricted"),
    ("restrn", 13, "no wake"),
    ("restrn", 14, "area to be avoided"),
    ("restrn", 27, "speed restricted"),
    ("restrn", 28, "overtaking prohibited"),
    ("restrn", 29, "overtaking of convoys by convoys prohibited"),
    ("restrn", 30, "passing or overtaking prohibited"),
    ("restrn", 31, "berthing prohibited"),
    ("restrn", 32, "berthing restricted"),
    ("restrn", 33, "making fast prohibited"),
    ("restrn", 34, "making fast restricted"),
    ("restrn", 35, "turning prohibited"),
    ("restrn", 36, "restricted fairway depth"),
    ("shptyp", 1, "general cargo vessel"),
    ("shptyp", 2, "container vessel"),
    ("shptyp", 3, "tanker"),
    ("shptyp", 4, "sailing vessel"),
    ("shptyp", 5, "fishing vessel"),
    ("shptyp", 6, "special purpose vessel."),
    ("shptyp", 7, "man of War"),
    ("shptyp", 8, "submarine"),
    ("shptyp", 9, "high speed craft"),
    ("shptyp", 10, "bulk carrier"),
    ("shptyp", 11, "seaplane"),
    ("shptyp", 12, "tugboat"),
    ("shptyp", 13, "passenger vessel"),
    ("shptyp", 14, "ferry"),
    ("shptyp", 15, "boat"),
    ("trshgd", 1, "containers"),
    ("trshgd", 2, "bulk goods"),
    ("trshgd", 3, "oil"),
    ("trshgd", 4, "fuel"),
    ("trshgd", 5, "chemicals"),
    ("trshgd", 6, "liquid goods"),
    ("trshgd", 7, "explosive goods"),
    ("trshgd", 8, "fish"),
    ("trshgd", 9, "cars"),
    ("trshgd", 10, "general cargo"),
    ("useshp", 1, "liner trade"),
    ("useshp", 2, "occasional professional shipping"),
    ("useshp", 3, "leisure"),
    ("verdat", 12, "Mean lower low water"),
    ("verdat", 31, "Local low water reference level"),
    ("verdat", 32, "Local high water reference level"),
    ("verdat", 33, "Local mean water reference level"),
    ("verdat", 34, "Equivalent height of water (German GlW)"),
    ("verdat", 35, "Highest Shipping Height of Water (German HSW)"),
    ("verdat", 36, "Reference low water level according to Danube Commission"),
    ("verdat", 37, "Highest shipping height of water according to Danube Commission"),
    ("verdat", 38, "Dutch river low water reference level (OLR)"),
    ("verdat", 39, "Russian project water level"),
    ("verdat", 40, "Russian normal backwater level"),
    ("verdat", 41, "Ohio River Datum"),
    ("watlev", 1, "partly submerged at high water"),
    ("watlev", 2, "always dry"),
    ("watlev", 3, "always under water/submerged"),
    ("watlev", 4, "covers and uncovers"),
    ("watlev", 8, "above mean water level"),
    ("watlev", 9, "below mean water level"),
];

/// The full name of an S-57 object class, e.g. "Buoy, cardinal" for BOYCAR.
pub fn object_class_name(acronym: &str) -> Option<&'static str> {
    OBJECT_CLASSES
        .binary_search_by(|(a, _)| (*a).cmp(acronym))
        .ok()
        .map(|i| OBJECT_CLASSES[i].1)
}

/// The meaning of an enumerated attribute value, e.g. CATCAM 1 is
/// "North Cardinal Mark". `None` when the attribute is not an enumeration or
/// the value is not one the standard lists.
pub fn attribute_value_name(acronym: &str, value: u32) -> Option<&'static str> {
    ATTRIBUTE_VALUES
        .binary_search_by(|(a, v, _)| (*a, *v).cmp(&(acronym, value)))
        .ok()
        .map(|i| ATTRIBUTE_VALUES[i].2)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_sorted_for_binary_search() {
        for w in OBJECT_CLASSES.windows(2) {
            assert!(w[0].0 < w[1].0, "{} then {}", w[0].0, w[1].0);
        }
        for w in ATTRIBUTE_VALUES.windows(2) {
            assert!((w[0].0, w[0].1) < (w[1].0, w[1].1), "{:?} then {:?}", &w[0], &w[1]);
        }
    }

    #[test]
    fn names_the_things_the_bubble_shows() {
        assert_eq!(object_class_name("BOYCAR"), Some("Buoy, cardinal"));
        assert_eq!(object_class_name("DEPARE"), Some("Depth area"));
        assert_eq!(object_class_name("NOSUCH"), None);
        assert_eq!(attribute_value_name("CATCAM", 1), Some("north cardinal mark"));
        assert_eq!(attribute_value_name("CATCAM", 99), None);
        assert_eq!(attribute_value_name("DRVAL1", 1), None);
    }
}
