//! S-52 Conditional Symbology (CS) Procedures
//!
//! CS procedures provide dynamic styling based on feature attributes
//! and mariner settings. They are invoked when a lookup table entry
//! references a procedure like "CS(DEPARE02)".
//!
//! Implemented procedures:
//! - DEPARE01/02: Depth area coloring based on safety depth
//! - DEPCNT02: Depth contour emphasis for safety contour
//! - SLCONS03: Shoreline construction styling (pier, wharf, breakwater, etc.)
//! - QUAPOS01: Position accuracy indicator (dashed for low accuracy)
//! - LIGHTS05/06: Light symbol selection based on color and range
//! - SNDFRM02: Sounding formatting and safety depth coloring

mod context;
mod datcvr;
mod depare;
mod depcnt;
mod lights;
mod obstrn;
mod qualin;
mod quapos;
mod resare;
mod restrn;
mod slcons;
mod sndfrm;
mod topmar;
mod wrecks;

pub use context::{CsContext, DepthAreaIndex};
pub use datcvr::datcvr01_instructions;
pub use depare::{depare02, depare02_color_token, depare02_instructions, DepthColorToken};
pub use depcnt::{depcnt02, depcnt02_params, is_safety_contour, DepthContourStyle};
pub use lights::{
    light_render_info, light_sector_info, lights06, lights06_symbol, litdsn01, LightRenderInfo,
    LightSectorInfo, LightSymbol,
};
pub use obstrn::{obstrn04, obstrn04_instructions, obstrn04_symbol, Obstrn04Result, ObstrnSymbol};
pub use qualin::qualin01_instructions;
pub use quapos::quapos01_instructions;
pub use resare::resare02_instructions;
pub use restrn::restrn01_instructions;
pub use slcons::slcons03_instructions;
pub use sndfrm::{sndfrm02, sounding_color, sounding_color_rgb, SoundingRenderInfo};
pub use topmar::topmar01_instructions;
pub use wrecks::{wrecks02, wrecks02_instructions, wrecks02_symbol, Wrecks02Result, WrecksSymbol};

use crate::s52::instruction::{RenderInstruction, SymbolRotation};
use crate::s52::MarinerSettings;
use crate::senc::Feature;

/// Execute a conditional symbology procedure by name.
///
/// # Arguments
/// * `procedure` - Procedure name like "DEPARE02" or "DEPCNT02"
/// * `feature` - The feature to process
/// * `settings` - Mariner settings
///
/// # Returns
/// Render instructions generated by the procedure, or None if unknown procedure.
pub fn execute_cs(
    procedure: &str,
    feature: &Feature,
    settings: &MarinerSettings,
    ctx: &CsContext,
) -> Option<Vec<RenderInstruction>> {
    match procedure {
        "DATCVR01" => Some(datcvr01_instructions(feature)),
        "DEPARE01" | "DEPARE02" => Some(depare02_instructions(feature, settings)),
        "DEPCNT02" => {
            let (pattern, width, color_token) = depcnt02_params(feature, settings);
            Some(vec![RenderInstruction::LineStyle {
                pattern,
                width,
                color: color_token.to_string(),
            }])
        }
        "SLCONS03" => Some(slcons03_instructions(feature, settings)),
        "QUAPOS01" => Some(quapos01_instructions(feature, settings)),
        "LIGHTS05" | "LIGHTS06" => {
            // light_render_info carries the flare's 135-degree rotation and the
            // ORIENT-derived rotation for directional lights; the instruction
            // stream is where that belongs, so the renderer has one source.
            // A light with a valid sector is drawn as a bounded arc, not a
            // symbol: s52cnsy.cpp LIGHTS06 replaces the symbol command with
            // CA(). navcore builds that arc in tiles/builder.rs from
            // light_sector_info, so the instruction stream carries nothing —
            // emitting the all-round symbol here would leave a ring the
            // renderer then has to throw away.
            if light_sector_info(feature).is_some() {
                return Some(Vec::new());
            }
            let info = light_render_info(feature, settings);
            Some(vec![RenderInstruction::Symbol {
                name: info.symbol_name.to_string(),
                rotation: info.rotation_deg.map(SymbolRotation::Degrees),
            }])
        }
        "OBSTRN04" => Some(obstrn04_instructions(feature, settings, ctx)),
        "WRECKS02" => Some(wrecks02_instructions(feature, settings, ctx)),
        "RESARE02" => Some(resare02_instructions(feature, settings)),
        "RESTRN01" => Some(restrn01_instructions(feature)),
        "QUALIN01" => Some(qualin01_instructions(feature)),
        "TOPMAR01" => Some(topmar01_instructions(feature, settings)),
        _ => None, // Unknown procedure
    }
}

/// Check if an instruction string contains a CS procedure reference.
///
/// Returns Some(procedure_name) if found, None otherwise.
pub fn extract_cs_procedure(instruction: &str) -> Option<&str> {
    // Look for CS(PROCNAME) pattern
    if let Some(start) = instruction.find("CS(") {
        let rest = &instruction[start + 3..];
        if let Some(end) = rest.find(')') {
            return Some(&rest[..end]);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The contours these depth cases were written against. Pinned here so they
    /// test the procedure rather than `MarinerSettings::default()`, which
    /// tracks s52plib's own defaults and has changed under them once already.
    fn test_contours() -> MarinerSettings {
        MarinerSettings {
            safety_depth: 10.0,
            safety_contour: 10.0,
            shallow_contour: 2.0,
            deep_contour: 30.0,
            ..Default::default()
        }
    }

    use crate::s52::instruction::LinePattern;
    use crate::senc::{AttributeValue, FeatureType, ObjectClass};

    fn make_depare(drval1: f64, drval2: f64) -> Feature {
        let mut attributes = crate::senc::Attributes::new();
        attributes.insert("DRVAL1", AttributeValue::Float(drval1));
        attributes.insert("DRVAL2", AttributeValue::Float(drval2));
        Feature {
            type_code: 0,
            object_class: ObjectClass::DepthArea,
            feature_type: FeatureType::Area,
            attributes,
            area_geometry: None,
            point_geometry: None,
            line_geometry: None,
            multipoint_geometry: None,
        }
    }

    #[test]
    fn test_execute_depare02() {
        let feature = make_depare(0.0, 3.0);
        let settings = test_contours();
        let instructions = execute_cs("DEPARE02", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::AreaColor { color, .. } = &instructions[0] {
            assert_eq!(color, "DEPVS"); // Very shallow
        } else {
            panic!("Expected AreaColor instruction");
        }
    }

    fn make_depcnt(valdco: f64) -> Feature {
        let mut attributes = crate::senc::Attributes::new();
        attributes.insert("VALDCO", AttributeValue::Float(valdco));
        Feature {
            type_code: 0,
            object_class: ObjectClass::DepthContour,
            feature_type: FeatureType::Line,
            attributes,
            area_geometry: None,
            point_geometry: None,
            line_geometry: None,
            multipoint_geometry: None,
        }
    }

    #[test]
    fn test_execute_depcnt02() {
        let feature = make_depcnt(10.0); // Safety contour
        let settings = test_contours();
        let instructions = execute_cs("DEPCNT02", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::LineStyle {
            pattern,
            width,
            color,
        } = &instructions[0]
        {
            assert_eq!(*pattern, LinePattern::Solid); // Accurate position = solid
            assert_eq!(*width, 2); // Thick for safety
            assert_eq!(color, "DEPSC");
        } else {
            panic!("Expected LineStyle instruction");
        }
    }

    fn make_depcnt_with_quapos(valdco: f64, quapos: i32) -> Feature {
        let mut attributes = crate::senc::Attributes::new();
        attributes.insert("VALDCO", AttributeValue::Float(valdco));
        attributes.insert("QUAPOS", AttributeValue::Integer(quapos));
        Feature {
            type_code: 0,
            object_class: ObjectClass::DepthContour,
            feature_type: FeatureType::Line,
            attributes,
            area_geometry: None,
            point_geometry: None,
            line_geometry: None,
            multipoint_geometry: None,
        }
    }

    #[test]
    fn test_execute_depcnt02_low_accuracy() {
        // Safety contour with low accuracy (QUAPOS=4) should be dashed
        let feature = make_depcnt_with_quapos(10.0, 4);
        let settings = test_contours();
        let instructions = execute_cs("DEPCNT02", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::LineStyle {
            pattern,
            width,
            color,
        } = &instructions[0]
        {
            assert_eq!(*pattern, LinePattern::Dashed); // Low accuracy = dashed
            assert_eq!(*width, 2); // Still thick for safety
            assert_eq!(color, "DEPSC");
        } else {
            panic!("Expected LineStyle instruction");
        }
    }

    #[test]
    fn test_unknown_procedure() {
        let feature = make_depare(0.0, 10.0);
        let settings = test_contours();
        assert!(execute_cs("UNKNOWN01", &feature, &settings, CsContext::EMPTY).is_none());
    }

    #[test]
    fn test_extract_cs_procedure() {
        assert_eq!(extract_cs_procedure("CS(DEPARE02)"), Some("DEPARE02"));
        assert_eq!(
            extract_cs_procedure("AC(DEPMD);CS(DEPARE02)"),
            Some("DEPARE02")
        );
        assert_eq!(extract_cs_procedure("AC(LANDA)"), None);
    }

    fn make_slcons(catslc: Option<i32>) -> Feature {
        let mut attributes = crate::senc::Attributes::new();
        if let Some(v) = catslc {
            attributes.insert("CATSLC", AttributeValue::Integer(v));
        }
        Feature {
            type_code: 0,
            object_class: ObjectClass::ShorelineConstruction,
            feature_type: FeatureType::Line,
            attributes,
            area_geometry: None,
            point_geometry: None,
            line_geometry: None,
            multipoint_geometry: None,
        }
    }

    fn make_feature_with_quapos(quapos: i32) -> Feature {
        let mut attributes = crate::senc::Attributes::new();
        attributes.insert("QUAPOS", AttributeValue::Integer(quapos));
        Feature {
            type_code: 0,
            object_class: ObjectClass::Coastline,
            feature_type: FeatureType::Line,
            attributes,
            area_geometry: None,
            point_geometry: None,
            line_geometry: None,
            multipoint_geometry: None,
        }
    }

    #[test]
    fn test_execute_slcons03_pier() {
        // Pier (CATSLC=4) is NOT a major structure per OpenCPN
        // Only wharf(6), mole(15), log ramp(16) are major structures
        let feature = make_slcons(Some(4)); // Pier
        let settings = test_contours();
        let instructions = execute_cs("SLCONS03", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::LineStyle {
            pattern,
            width,
            color,
        } = &instructions[0]
        {
            assert_eq!(*pattern, LinePattern::Solid);
            assert_eq!(*width, 2); // Minor structure (only 6/15/16 are major)
            assert_eq!(color, "CSTLN");
        } else {
            panic!("Expected LineStyle instruction");
        }
    }

    #[test]
    fn test_execute_slcons03_breakwater() {
        let feature = make_slcons(Some(1)); // Breakwater
        let settings = test_contours();
        let instructions = execute_cs("SLCONS03", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::LineStyle { width, .. } = &instructions[0] {
            assert_eq!(*width, 2); // Thinner for minor structure
        } else {
            panic!("Expected LineStyle instruction");
        }
    }

    #[test]
    fn test_execute_quapos01_accurate() {
        let feature = make_feature_with_quapos(1); // Surveyed
        let settings = test_contours();
        let instructions = execute_cs("QUAPOS01", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::LineStyle { pattern, .. } = &instructions[0] {
            assert_eq!(*pattern, LinePattern::Solid);
        } else {
            panic!("Expected LineStyle instruction");
        }
    }

    #[test]
    fn test_execute_quapos01_low_accuracy() {
        let feature = make_feature_with_quapos(4); // Approximate
        let settings = test_contours();
        let instructions = execute_cs("QUAPOS01", &feature, &settings, CsContext::EMPTY).unwrap();
        assert_eq!(instructions.len(), 1);
        if let RenderInstruction::LineComplex { name } = &instructions[0] {
            assert_eq!(name, "LOWACC21");
        } else {
            panic!("Expected LineComplex instruction");
        }
    }
}
